Python/mysit/blog/urls.py
from django.urls import path,include,re_path
from . import views
urlpatterns = [
path('blog/',views.home),
path('article/(?P<article_id>[0-9]+)',views.article_page, name = 'article_page'),
path('edit/(?P<article_id>[0-9]+)',views.edit_page, name = 'edit_page'),
path('edit/action',views.edit_action, name = 'edit_action'),
]
app_name = 'blog'

Python/mysit/mysit/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include("blog.urls",'blog')),
]

Python/mysit/blog/models.py
from django.db import models

# Create your models here.
#定义字段
class Ariticle(models.Model):
    title = models.CharField(max_length=20,default="title")
    content = models.TextField(null=True)

    def __str__(self):
        return self.title

Python/mysit/blog/views.py
from django.shortcuts import render
from . import models
# Create your views here.

def home(request):
    articles = models.Ariticle.objects.all()
    return render(request,"blog/templates/message_form.html",{'key':articles})


def article_page(request,article_id):
    article = models.Ariticle.objects.get(pk=article_id)
    return render(request, 'blog/templates/article_page.html', {'article':article})

def edit_page(request,article_id):
    if str(article_id) == '0':
        return render(request,"blog/templates/edit_page.html")
    article = models.Ariticle.objects.get(pk = article_id)
    return render(request, "blog/templates/edit_page.html",{'article' : article})

def edit_action(request):
    title = request.POST.get("title","TITLE")
    content = request.POST.get("content", "CONTENT")
    article_id = request.POST.get('article_id','0')

    if article_id == '0':
        models.Ariticle.objects.create(title=title, content=content)
        articles = models.Ariticle.objects.all()
        return render(request,"blog/templates/message_form.html",{'key':articles})

    article = models.Ariticle.objects.get(pk = article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request, "blog/templates/article_page.html", {'article': article})

Python/mysit/blog/templates/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article page</title>
</head>
<body>
<h1>{{article.title}}</h1>
<br/>
<h3>{{article.content}}</h3>
<br/>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

Python/mysit/blog/templates/edit_page.html
<!DOCTYPE html>
<html lang="en" xmlns:default="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <title>edit_page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}

    <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}">
    <label>文章标题
        <input type="text" name="title" value="{{ article.title }}"/>
    </label>
    <br/>
    <label>文章内容
        <input type="text" name="content" value="{{article.content}}"/>
    </label>
    <br/>

    <input type="submit" name="提交"/>
</form>
</body>
</html>

Python/mysit/blog/templates/message_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="../../static/css/style.css"/>
</head>
<body>
<a href="{% url 'blog:edit_page' 0 %}">新文章</a>
<br/>
{% for article in key %}
<a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a>
<br/>
{% endfor %}
<form action="/form/" method="post" class="smart-green">
    <h1>留言信息
        <span>请留下你的信息.</span>
    </h1>
    <label>
        <span>姓名 :</span>
        <input id="name" type="text" name="name" class="error" placeholder="请输入您的姓名"/>
        <div class="error-msg"></div>
    </label>

    <label>
        <span>邮箱 :</span>
        <input id="email" type="email" value="" name="email" placeholder="请输入邮箱地址"/>
        <div class="error-msg"></div>
    </label>

    <label>
        <span>联系地址 :</span>
        <input id="address" type="text" value="" name="address" placeholder="请输入联系地址"/>
        <div class="error-msg"></div>
    </label>

    <label>
        <span>留言 :</span>
        <textarea id="message" name="message"  placeholder="请输入你的建议"></textarea>
        <div class="error-msg"></div>
    </label>
    <div class="success-msg"></div>
    <label>
        <span>&nbsp;</span>
        <input type="submit" class="button" value="提交"/>
    </label>
    <input type='hidden' name='csrfmiddlewaretoken' value='SfHkbL4feo1G00sJQtbO7TtLN4c2BUwa' />
</form>

</body>
</html>